### ISSUE TITLE
Error "unable to recover the password due to clevis failures"

### ISSUE THREAD

**Issue by benalexau** [anatol/booster#152]
I just upgraded an Arch Linux server from package `booster` 0.7-2 to 0.7-3. The server runs `clevis` package version 18-1 (since July 2021). Booster no longer unlocks using Clevis. The debug log is:

```
[    0.090528] Kernel command line: initrd=\intel-ucode.img initrd=\booster-linux.img rd.luks.name=4cc2f0c1-44bd-49cb-9d6f-7de7cb715e8e=root root=/dev/mapper/root booster.log=debug,console
[   55.320148] booster: recovering clevis token #0 failed: unable to recover the password due to clevis failures
```

I was able to enter the password manually and boot. I attempted to rebind the key slot as follows:

```
clevis luks list -d /dev/mmcblk0p2
clevis luks unbind -d /dev/mmcblk0p2 -s 1
clevis luks bind -y -k - -d /dev/mmcblk0p2 tang '{"url":"http://tang.domain.com"}'
clevis luks list -d /dev/mmcblk0p2
```

A `curl http://tang.domain.com/adv` returns a Tang payload as expected.

I also attempted to `/usr/lib/booster/regenerate_images` with the original `booster.yaml`:

```
network:
  dhcp: on

# see https://github.com/anatol/booster/issues/90
modules_force_load: sdhci,mmc_block,sdhci_pci
```

Any suggestions on what else to try?

**Comment by anatol** [comment]
Could you please try version 0.8 from testing and see if you still have this issue?

**Comment by anatol** [comment]
The only change for Arch Linux 0.7-3 package is a rebuild against golang 1.18. And it makes me believe the issue you see is related to EllipticCurve changes in 1.18. This golang version changed the behavior of `Add()` function and does not normalize negative points anymore; instead, it started returning a random result (that is a confusing behavior in my opinion). 

The issue has been fixed by this commit https://github.com/anatol/clevis.go/commit/f2752399a49b1ca6b93011e873bba650e6c30411 and been pulled into `booster` master a long time ago but was not added into 0.7-3. This was a fault on my side.

Given that 0.8 has been released almost a month ago it is better to move to booster 0.8. This particular issue should be fixed now.

**Comment by benalexau** [comment]
Thanks @anatol. I have upgraded to `booster` 0.8-1 on half a dozen servers thus far and it is definitely fixed in that version.
