### ISSUE TITLE
Kernel panic with an Intel 10-Gigabit X540-AT2 card

### ISSUE THREAD

**Issue by benalexau** [anatol/booster#31]
I undertook a fresh install of Arch Linux on a spare Supermicro server, including Booster 0.2-1 from the official Arch binary packages during `pacstrap` and a LUKS encrypted partition. Booster was configured for DHCP networking during the `arch-chroot` stage. The DHCP server returns a DNS server on the same subnet.

The initial reboot was successful and Tang-based unlocking was then configured using `clevis luks bind -d /dev/sda2 tang '{"url": "http://cwdsrrkms1.acegi.com.au"}'` (this host is on the same subnet as the host; ie no gateway is required). After rebooting the following kernel panic was displayed:

![image](https://user-images.githubusercontent.com/718596/108346714-cc373200-7233-11eb-96c0-0b69bf553b30.png)

This server includes an Intel 10-Gigabit X540-AT2 (`ensf30`) card in addition to the inbuilt Intel I350 Gigabit Network Controller on the motherboard.

Following the above failed boot I restarted with a live image, disabled the network in `/etc/booster.yaml`, reinstalled Booster, and rebooted without issue.

Any thoughts on how to overcome the kernel panic?

**Comment by anatol** [comment]
It is a known race condition between closing udev reader and reading udev event - https://github.com/anatol/booster/issues/22. See also https://github.com/s-urbaniak/uevent/issues/3.

It has been fixed in master https://github.com/anatol/booster/commit/f51031a73f7eeb8e6d3854d5ec031dc3f63d18a5

So as a workaround you can try to use `booster-git` package from AUR until booster 0.3 is released to the official repo.

**Comment by benalexau** [comment]
Thanks @anatol.

Using AUR `booster-giit` (built against bc5b2553685478c70eb4004015a146eabdb868a0) fixed this issue and the server booted with Tang-based unlocking without any issue.
