### ISSUE TITLE
Error "Too many open files" when creating universal image

### ISSUE THREAD

**Issue by Sporif** [anatol/booster#76]
I'm getting this error fairly often when creating a universal image with strip enabled, lines like:
`/usr/lib/modules/rmd256.ko: pipe2: too many open files` or
`/usr/lib/modules/842_compress.ko: open /dev/null: too many open files`

**Comment by anatol** [comment]
It happens because you build a universal image (i.e. it contains a lot of modules) and `strip` option enabled. When many `strip` commands are executed in parallel then it requires many files (binaries, shared libraries, etc) to be open.

Current open file limit is ridiculously low, it is something like 1024 files (`ulimit -n`). Opening many files leads to this limit exhaustion.

To avoid this error message please increase the file limit https://wiki.archlinux.org/index.php/Limits.conf (option `nofile`) to something more reasonable (8192 at least).

Or you can disable `strip` option.

**Comment by mvdan** [comment]
FYI, Go 1.19 will do this for you automatically: https://github.com/golang/go/issues/46279

Perhaps worth adding a TODO to remove your workaround in a year or two, once you can drop support for Go 1.18 and older. Then there's less code to maintain :)

**Comment by anatol** [comment]
Oh, I did not know about this restriction. Thanks for pointing it out.
